### PR TITLE
Fix/make traits initialised by class

### LINKED ISSUE #269: Graphite does not work without icingadb anymore
Navigating to any host or service gives

    Trait "Icinga\Module\Icingadb\Common\Macros" not found

    #0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
    #1 {main}

## Your Environment
* Module version (System - About): 2915e4a4d2bf1e5bc72bdd967862f8e010ff49b6 https://github.com/Icinga/icingaweb2-module-graphite/pull/259
* Icinga Web 2 version and modules (System - About): 2.9.5
* Icinga 2 version (`icinga2 --version`): r2.13.2-1
* Operating System and version: Ubuntu 21.10
* Webserver, PHP versions: PHP 8.0.8

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fixes #269

### CODE REVIEW

File: library/Graphite/Graphing/MetricsQuery.php [hunk 1]
```diff
@@ -154,8 +152,8 @@ public function fetchColumn()
                 } else {
                     $workaroundMacro = $migratedMacro;
                 }
-
-                $result = $this->resolveMacro($workaroundMacro, $this->object);
+                $icingadbMacros = IcingadbUtils::getInstance();
```
Comment (nilmerg) [inline library/Graphite/Graphing/MetricsQuery.php:155]: Empty line after .. closing braces, please

File: library/Graphite/Util/IcingadbUtils.php [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+namespace Icinga\Module\Graphite\Util;
+
+use Icinga\Module\Icingadb\Common\Auth;
+use Icinga\Module\Icingadb\Common\Database;
+use Icinga\Module\Icingadb\Common\Macros;
+
+/**
+ * Collection of possible host states.
+ */
```
Comment (nilmerg) [inline library/Graphite/Util/IcingadbUtils.php:13]: Hm?

**Review by nilmerg — CHANGES_REQUESTED** [review]
