### PR TITLE
Make graphite path wildcards work

### LINKED ISSUE #220: Url Encode fails on [] range chars
I try to use the range filter method from graphite but the encoding fails horribly!

`suite.value = "$service_name_template$.perfdata.suite_[a-z]*.value"`

Results in this: 

`'http://localhost:8000/metrics/expand?query=icinga2.hostname.services.servicename.passive.perfdata.suite_%5B%5B%5Da-z%5B%5D%5D%2A.value'`

## Your Environment

* Module version (System - About): 1.1.0
* Icinga Web 2 version and modules (System - About): 2.7.1
* Icinga 2 version (`icinga2 --version`): 2.10.5_1
* Graphite (carbon, web, whisper) version: 1.1.5 
* Operating System and version: Ubuntu 16.04 LTS 
* Webserver, PHP versions: 7.2.19-0ubuntu0.18.04.2 apache2

### PR DESCRIPTION
**Pull request by sukhwinder33445**
resolves #220

### CODE REVIEW

**Comment by sukhwinder33445** [comment]
Tests:

Tested with the `users.ini` file. Changed the `[users.metrics_filters]` for tests.

users = "$service_name_template$.perfdata.us[a-z]rs.value"   ✅ 
users = "$service_name_template$.perfdata.us[a-z]rs.value"   ✅ 
users = "$service_name_template$.perfdata.us[a-z]rs.value"   ✅ 
users = "$service_name_template$.perfdata.us[a-z]rs.value"   ✅

File: library/Graphite/Graphing/GraphiteWebClient.php [hunk 1]
```diff
@@ -94,13 +94,19 @@ public function request(Url $url, $method = 'GET', array $headers = [], $body =
      */
     public function escapeMetricPath($metricPath)
     {
-        return preg_replace_callback(
+        // TODO: Don't know what is the reason behind this?
+        // it changes '.u[sd]ers.value' into '.u[[]sd[]].value'
+        // and cause empty result at the end
```
Comment (nilmerg) [inline library/Graphite/Graphing/GraphiteWebClient.php:99]: I don't either. This was introduced by 839ca7e6185f9e5bd10c5d7e95b1a4f5f734d27b. @Al2Klimov any hint?

Comment (Al2Klimov) [reply library/Graphite/Graphing/GraphiteWebClient.php:99]: Graphite Web takes patterns, not literal strings. That was intended to make [ ] working in metric names.

Comment (nilmerg) [reply library/Graphite/Graphing/GraphiteWebClient.php:99]: I see. Though we cannot remove the method. It's just applied incorrectly. It cannot be used to escape the entire metric path, only selected parts. I suppose it's sufficient to escape the results of macros. (i.e. The ones inside `$host_name_template$` and `$service_name_template$`) Additionally, the documentation should describe how to escape `[ ]` and `{ }` in metric filters of templates.

So that this works:

host.name = foo[bar]
host.check_command = rab[oof]
host_name_template = icinga2.$host.name$.host.$host.check_command$
users = $host_name_template$.perfdata.us[a-z]rs.value
result = icinga2.foo[[]bar[]].host.rab[[]oof[]].perfdata.us[a-z]rs.value

File: library/Graphite/Util/MacroTemplate.php [hunk 2]
```diff
@@ -200,6 +205,22 @@ protected function getReverseResolvePattern()
...
             $this->reverseResolvePattern = implode($result);
+
+            $searchReplace = [
+                '\[' => '[', //Don't quote [, -, ]
+                '\-' => '-',
+                '\]' => ']',
+                '\{' => '(', // change graphite list syntax to regex
+                ','  => '|',
+                '\}' => ')',
+                '\*' => '(.*)' // change graphite * syntax to regex
```
Comment (nilmerg) [inline library/Graphite/Util/MacroTemplate.php:216]: Is this why you need to break out of the foreach above? Is this still required if you make this a non-capturing group?

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Comment by sukhwinder33445** [comment]
Tests:

Tested with the disk.ini file. Changed the [users.metrics_filters] for tests.

✅ value = "$service_name_template$.perfdata.$disk:{_etc_hostname,_data}$.value"
✅ value = "$service_name_template$.perfdata.$disk:{_etc*,_data}$.value"
✅ value = "$service_name_template$.perfdata.$disk:{_et[abc]_hostname,_data}$.value"

File: library/Graphite/Util/MacroTemplate.php [hunk 3]
```diff
@@ -38,8 +52,16 @@ class MacroTemplate
...
     public function __construct($template, $macroCharacter = '$')
     {
+        $this->orgTemplate = $template;
         $this->macroCharacter = $macroCharacter;
         $this->template = explode($macroCharacter, $template);
+        foreach ($this->template as $key => $value) {
+            if (preg_match('/([^:]+):(.+)/', $value, $match)) {
+                    $wildCardKey = $match[1];
+                    $this->template[$key] = $wildCardKey;
+                    $this->wildCards[$wildCardKey] = $match[2];
```
Comment (nilmerg) [inline library/Graphite/Util/MacroTemplate.php:62]: indentation?

File: doc/04-Templates.md [hunk 4]
```diff
@@ -86,10 +86,24 @@ macro in place for the actual perfdata-label:
 
     $host_name_template$.perfdata.$perfdata_label$.value
 
+You can also use wildcards. To define a wildcard, please use the following syntax:
+
+Enter the micro name, then `:` and then the syntax for the wildcard. The `:` lets the graphite module
+know that a wildcard exists here.
```
Comment (nilmerg) [inline doc/04-Templates.md:92]: I'd leave that out. The examples below make it clear enough.

File: doc/04-Templates.md [hunk 5]
```diff
@@ -86,10 +86,24 @@ macro in place for the actual perfdata-label:
...
+
+    $micro:wildcard syntax here$
```
Comment (nilmerg) [inline doc/04-Templates.md:94]: micro -> macro

File: doc/04-Templates.md [hunk 6]
```diff
@@ -86,10 +86,24 @@ macro in place for the actual perfdata-label:
...
+
+    $perfdata_label:{abc,def}$
+    $perfdata_label:{a*c,de*}$
+    $perfdata_label:{a[vbn]c,def}$
+
 > **Note:**
 >
 > The name of the macro for the perfdata-label is also arbitrary. You may as
-> well use a more descriptive name such as `$disk$` for the disk check.
+> well use a more descriptive name such as `$disk$` for the disk check. The `$disk$`
```
Comment (nilmerg) [inline doc/04-Templates.md:105]: The `$disk$`? Either drop the `The` or continue afterwards with `macro`: So either `$disk$ is...` or `The $disk$ macro is...`

Comment (nilmerg) [reply doc/04-Templates.md:105]: at the end of the sentence the same please.

**Review by nilmerg — APPROVED** [review]
